# Generated by Django 3.2.9 on 2022-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', 'initGroupUSer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccess',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
