# Generated by Django 3.2.9 on 2022-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_apiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='groupAccess',
            field=models.ManyToManyField(default=None, to='user_management.GroupAccess'),
        ),
    ]
