# Generated by Django 3.2.9 on 2022-02-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_apiuser_groupaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIstatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=255)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.apiuser')),
            ],
        ),
    ]
