# Generated by Django 3.2.9 on 2022-02-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_apistatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistatistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.apiuser'),
        ),
    ]
