# Generated by Django 3.2.9 on 2021-11-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bottle', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='client.client')),
            ],
            options={
                'verbose_name': 'Scale',
                'verbose_name_plural': 'Scales',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='client.client')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(blank=True, default='')),
                ('wine_name', models.CharField(blank=True, default='', max_length=25)),
                ('country', models.TextField(blank=True, default='')),
                ('region', models.TextField(blank=True, default='')),
                ('subregion', models.TextField(blank=True, default='')),
                ('appellation', models.TextField(blank=True, default='')),
                ('label', models.TextField(blank=True, default='')),
                ('grape_assemble', models.TextField(blank=True, default='')),
                ('colour', models.TextField(blank=True, default='')),
                ('type', models.TextField(blank=True, default='')),
                ('vintage', models.TextField(blank=True, default='')),
                ('winemaker', models.TextField(blank=True, default='')),
                ('certification', models.TextField(blank=True, default='')),
                ('volume', models.TextField(blank=True, default='')),
                ('weight', models.TextField(blank=True, default='')),
                ('alcohol', models.FloatField(blank=True, default=0)),
                ('comment', models.TextField(blank=True, default='')),
                ('ranking', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('price_pre_taxe', models.FloatField(blank=True, default=0)),
                ('vat', models.FloatField(blank=True, default=0)),
                ('price_with_taxe', models.FloatField(blank=True, default=0)),
                ('status', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='', max_length=5)),
                ('bottle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to='bottle.bottle')),
                ('scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocklists', to='stock.scale')),
            ],
            options={
                'verbose_name': 'Stock list',
                'verbose_name_plural': 'Stock lists',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('quantity_available', models.IntegerField(blank=True, default=0)),
                ('quantity_ordered', models.IntegerField(blank=True, default=0)),
                ('quantity_reserved', models.IntegerField(blank=True, default=0)),
                ('stocklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.stocklist')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='BottlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('currency', models.CharField(blank=True, default='', max_length=5)),
                ('category', models.TextField(blank=True, default='')),
                ('promo_price', models.FloatField(blank=True, default=0)),
                ('start_promotion_date', models.DateField(auto_now_add=True)),
                ('end_promotion_date', models.DateField(auto_now_add=True)),
                ('stocklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottle_prices', to='stock.stocklist')),
            ],
            options={
                'verbose_name': 'Bottle price',
                'verbose_name_plural': 'Bottles prices',
            },
        ),
    ]
