# Generated by Django 3.2.9 on 2021-11-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottleprice',
            name='end_promotion_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bottleprice',
            name='start_promotion_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
