# Generated by Django 3.2.9 on 2022-02-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20220207_1115'),
        ('stock', '0003_auto_20211214_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='client',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stocklist',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stocklist',
            name='bottle',
        ),
        migrations.RemoveField(
            model_name='stocklist',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='client',
        ),
        migrations.DeleteModel(
            name='BottlePrice',
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockList',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
