# Generated by Django 3.2.9 on 2021-11-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('client', '0002_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='client.client'),
        ),
        migrations.AlterField(
            model_name='command',
            name='id_stocklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='stock.stocklist'),
        ),
    ]
