# Generated by Django 3.2.9 on 2021-11-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20211123_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id_customer',
        ),
    ]
