# Generated by Django 3.2.9 on 2021-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_message_id_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_customer',
            field=models.TextField(blank=True, default='', unique=True),
        ),
    ]
