runtime: custom
env: flex
handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static
- url: /.*
  script: auto
entrypoint: gunicorn -b :$PORT main_api.wsgi

beta_settings:
  cloud_sql_instances: api-etoh-back-prod:europe-west1:bd-standard

runtime_config:
  python_version: 3
# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
