# Generated by Django 3.2.9 on 2021-11-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0007_alter_agingdefault_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominationwine',
            name='wine_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bottle.winecdc'),
        ),
    ]
