# Generated by Django 3.2.9 on 2021-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_denominationwine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemble',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
