# Generated by Django 3.2.9 on 2022-02-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0019_auto_20220207_1115'),
        ('appellation', '0021_auto_20220207_1115'),
        ('core', '0006_alphabet_country_language'),
        ('wine', '0008_auto_20220207_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assemble',
        ),
        migrations.AddField(
            model_name='language',
            name='id_alphabet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.alphabet'),
        ),
        migrations.AddField(
            model_name='country',
            name='id_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core.language'),
        ),
        migrations.AddField(
            model_name='country',
            name='zone_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='appellation.adminzone'),
        ),
    ]
