# Generated by Django 3.2.9 on 2021-11-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('hierarchy', models.TextField(blank=True, default='')),
                ('geom', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appellation.adminzone')),
            ],
            options={
                'verbose_name': 'Zone Admins',
            },
        ),
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('name_dgc', models.CharField(blank=True, default='', max_length=255)),
                ('label', models.TextField(blank=True, default='')),
                ('etymology', models.TextField(blank=True, default='')),
                ('hierarchy', models.TextField(blank=True, default='')),
                ('volume_production', models.IntegerField(blank=True, default=0)),
                ('denomination_wine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appellations', to='core.denominationwine')),
            ],
            options={
                'verbose_name': 'Appelations',
            },
        ),
        migrations.CreateModel(
            name='AppellationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('geom', models.TextField(blank=True, default='')),
                ('ground', models.TextField(blank=True, default='')),
                ('subsoil', models.TextField(blank=True, default='')),
                ('climat', models.TextField(blank=True, default='')),
                ('min_elevetion', models.FloatField(blank=True, default=0)),
                ('max_elevetion', models.FloatField(blank=True, default=0)),
                ('average_elevetion', models.FloatField(blank=True, default=0)),
                ('min_precipitation', models.FloatField(blank=True, default=0)),
                ('max_precipitation', models.FloatField(blank=True, default=0)),
                ('average_precipitation', models.FloatField(blank=True, default=0)),
                ('situation', models.TextField(blank=True, default='')),
                ('sunshine', models.TextField(blank=True, default='')),
                ('min_temperature', models.FloatField(blank=True, default=0)),
                ('max_temperature', models.FloatField(blank=True, default=0)),
                ('average_temperature', models.FloatField(blank=True, default=0)),
                ('orientation', models.TextField(blank=True, default='')),
                ('air', models.IntegerField(blank=True, default=0)),
                ('geology', models.TextField(blank=True, default='')),
                ('pedology', models.TextField(blank=True, default='')),
                ('lithology', models.TextField(blank=True, default='')),
                ('hierarchy', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appellation.appellationzone')),
            ],
            options={
                'verbose_name': 'Appelation Zones',
            },
        ),
        migrations.CreateModel(
            name='ViticultureZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('hierarchy', models.TextField(blank=True, default='')),
                ('geom', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appellation.viticulturezone')),
            ],
            options={
                'verbose_name': 'Viticulture zones',
            },
        ),
        migrations.CreateModel(
            name='PlotZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.TextField(blank=True, default='')),
                ('code_insee', models.CharField(blank=True, default='', max_length=25)),
                ('prefix', models.CharField(blank=True, default='', max_length=25)),
                ('section', models.CharField(blank=True, default='', max_length=25)),
                ('number', models.CharField(blank=True, default='', max_length=25)),
                ('geom', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appellation.plotzone')),
                ('zone_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot_zone', to='appellation.adminzone')),
                ('zone_appelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot_zones', to='appellation.appellationzone')),
            ],
            options={
                'verbose_name': 'Plot Zones ',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('code_two', models.CharField(blank=True, default='', max_length=2)),
                ('code_three', models.CharField(blank=True, default='', max_length=3)),
                ('zone_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='appellation.adminzone')),
            ],
            options={
                'verbose_name': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='AppellationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_authorization', models.TextField(blank=True, default='')),
                ('appellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appellation_type', to='appellation.appellation')),
            ],
            options={
                'verbose_name': 'Appellation Types',
            },
        ),
        migrations.CreateModel(
            name='AppellationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting', models.TextField(blank=True, default='')),
                ('definition', models.TextField(blank=True, default='')),
                ('file_name', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('media_photo', models.TextField(blank=True, default='')),
                ('gps_coordinates', models.TextField(blank=True, default='')),
                ('appellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appellation_zone_photos', to='appellation.appellationzone')),
            ],
            options={
                'verbose_name': 'Appellation Photo',
                'verbose_name_plural': 'Appellation Photos',
            },
        ),
        migrations.CreateModel(
            name='AppellationColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_authorization', models.TextField(blank=True, default='')),
                ('color_authorization', models.TextField(blank=True, default='')),
                ('percentage', models.IntegerField(blank=True, default=0)),
                ('appellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appellation_colour', to='appellation.appellation')),
            ],
            options={
                'verbose_name': 'Appellation Colours',
            },
        ),
        migrations.AddField(
            model_name='appellation',
            name='zone_appelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appellation', to='appellation.appellationzone'),
        ),
        migrations.AddField(
            model_name='adminzone',
            name='zone_appelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_zones', to='appellation.appellationzone'),
        ),
    ]
