# Generated by Django 3.2.9 on 2021-11-23 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20211123_1048'),
        ('appellation', '0002_viticulturezone_zone_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellation',
            name='denomination_wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appellations', to='wine.denominationwine'),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
