# Generated by Django 3.2.9 on 2021-11-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0003_auto_20211123_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminzone',
            options={'verbose_name': 'Zone Admin', 'verbose_name_plural': 'Zone Admins'},
        ),
        migrations.AlterModelOptions(
            name='appellation',
            options={'verbose_name': 'Appelation', 'verbose_name_plural': 'Appelations'},
        ),
        migrations.AlterModelOptions(
            name='appellationcolour',
            options={'verbose_name': 'Appellation Colour', 'verbose_name_plural': 'Appellation Colours'},
        ),
        migrations.AlterModelOptions(
            name='appellationtype',
            options={'verbose_name': 'Appellation Type', 'verbose_name_plural': 'Appellation Types'},
        ),
        migrations.AlterModelOptions(
            name='appellationzone',
            options={'verbose_name': 'Appelation Zone', 'verbose_name_plural': 'Appelation Zones'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='plotzone',
            options={'verbose_name': 'Plot Zone', 'verbose_name_plural': 'Plot Zones'},
        ),
        migrations.AlterModelOptions(
            name='viticulturezone',
            options={'verbose_name': 'Viticulture zone', 'verbose_name_plural': 'Viticulture zones'},
        ),
    ]
