# Generated by Django 3.2.9 on 2021-11-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0004_auto_20211123_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appellationphoto',
            old_name='appellation',
            new_name='appellation_zone',
        ),
    ]
