# Generated by Django 3.2.9 on 2021-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0006_alter_appellationphoto_gps_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellationphoto',
            name='gps_coordinates',
            field=models.TextField(blank=True, default=''),
        ),
    ]
