# Generated by Django 3.2.9 on 2021-11-25 13:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0011_alter_appellationphoto_gps_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminzone',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geo'),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='gps_coordinates',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geo'),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geo'),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geo'),
        ),
        migrations.AlterField(
            model_name='viticulturezone',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='geo'),
        ),
    ]
