# Generated by Django 3.2.9 on 2021-11-25 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0012_auto_20211125_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminzone',
            name='geom',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='gps_coordinates',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='geom',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='geom',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='viticulturezone',
            name='geom',
            field=models.TextField(blank=True, default=''),
        ),
    ]
