# Generated by Django 3.2.9 on 2021-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0012_alter_winemaker_gps_location'),
        ('appellation', '0014_auto_20211125_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellation',
            name='sugar_dose',
            field=models.ManyToManyField(blank=True, to='bottle.SugarDose'),
        ),
    ]
