# Generated by Django 3.2.9 on 2021-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0012_alter_winemaker_gps_location'),
        ('appellation', '0015_appellation_sugar_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellation',
            name='sugar_dose',
            field=models.ManyToManyField(blank=True, related_name='appellations', to='bottle.SugarDose'),
        ),
    ]
