# Generated by Django 3.2.9 on 2021-12-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20211209_1129'),
        ('appellation', '0016_alter_appellation_sugar_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellation',
            name='sugar_dose',
            field=models.ManyToManyField(blank=True, related_name='appellations', to='wine.SugarDose'),
        ),
    ]
