# Generated by Django 3.2.9 on 2021-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0017_alter_appellation_sugar_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminzone',
            name='hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminzone',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='etymology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='name_dgc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='volume_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationcolour',
            name='color_authorization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationcolour',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationcolour',
            name='type_authorization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='media_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='shooting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationtype',
            name='type_authorization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='air',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='average_elevetion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='average_precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='average_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='climat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='geology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='ground',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='lithology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='max_elevetion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='max_precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='max_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='min_elevetion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='min_precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='min_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='orientation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='pedology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='situation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='subsoil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appellationzone',
            name='sunshine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code_three',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code_two',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='code_insee',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='prefix',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='plotzone',
            name='section',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='viticulturezone',
            name='hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viticulturezone',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
