# Generated by Django 3.2.9 on 2021-12-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0019_auto_20211214_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appellation',
            old_name='name_english_alpahbet_latin',
            new_name='name_english_alphabet_latin',
        ),
        migrations.RenameField(
            model_name='appellation',
            old_name='name_origin_alpahbet_latin',
            new_name='name_origin_alphabet_latin',
        ),
        migrations.RenameField(
            model_name='appellation',
            old_name='name_origin_alpahbet_origin',
            new_name='name_origin_alphabet_origin',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_english_alpahbet_latin',
            new_name='name_english_alphabet_latin',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_origin_alpahbet_latin',
            new_name='name_origin_alphabet_latin',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_origin_alpahbet_origin',
            new_name='name_origin_alphabet_origin',
        ),
        migrations.RenameField(
            model_name='viticulturezone',
            old_name='name_english_alpahbet_latin',
            new_name='name_english_alphabet_latin',
        ),
        migrations.RenameField(
            model_name='viticulturezone',
            old_name='name_origin_alpahbet_latin',
            new_name='name_origin_alphabet_latin',
        ),
        migrations.RenameField(
            model_name='viticulturezone',
            old_name='name_origin_alpahbet_origin',
            new_name='name_origin_alphabet_origin',
        ),
    ]
