# Generated by Django 3.2.9 on 2022-02-07 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0020_auto_20211214_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppellationSyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LinkAppDvitivini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LinkZappZadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='AppellationColour',
            new_name='Color',
        ),
        migrations.RemoveField(
            model_name='country',
            name='zone_admin',
        ),
        migrations.AlterModelOptions(
            name='appellation',
            options={'verbose_name': 'Appellation', 'verbose_name_plural': 'Appellation'},
        ),
        migrations.RenameField(
            model_name='appellationtype',
            old_name='appellation',
            new_name='id_app',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='air',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='average_elevetion',
            new_name='elevetion_average',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='average_precipitation',
            new_name='elevetion_max',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='average_temperature',
            new_name='elevetion_min',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='max_elevetion',
            new_name='precipitation_average',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='max_precipitation',
            new_name='precipitation_max',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='max_temperature',
            new_name='precipitation_min',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='min_elevetion',
            new_name='temperature_average',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='min_precipitation',
            new_name='temperature_max',
        ),
        migrations.RenameField(
            model_name='appellationzone',
            old_name='min_temperature',
            new_name='temperature_min',
        ),
        migrations.RemoveField(
            model_name='adminzone',
            name='zone_appelation',
        ),
        migrations.RemoveField(
            model_name='appellation',
            name='denomination_wine',
        ),
        migrations.RemoveField(
            model_name='appellation',
            name='sugar_dose',
        ),
        migrations.AddField(
            model_name='appellation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
