# Generated by Django 3.2.9 on 2022-02-07 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0019_auto_20220207_1115'),
        ('appellation', '0021_auto_20220207_1115'),
        ('productspec', '0001_initial'),
        ('wine', '0008_auto_20220207_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellation',
            name='dosage',
            field=models.ManyToManyField(blank=True, related_name='appellations', to='productspec.SugarDose'),
        ),
        migrations.AddField(
            model_name='appellation',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appellationtype',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appellationtype',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appellationzone',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appellationzone',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='viticulturezone',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='viticulturezone',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appellationphoto',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='appellationphoto',
            table='appellation_image',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='linkzappzadmin',
            name='id_za',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appellation.appellationzone'),
        ),
        migrations.AddField(
            model_name='linkzappzadmin',
            name='id_zadm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appellation.adminzone'),
        ),
        migrations.AddField(
            model_name='linkappdvitivini',
            name='id_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appellation.appellation'),
        ),
        migrations.AddField(
            model_name='linkappdvitivini',
            name='id_dvitivini_authorized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productspec.denominationwine'),
        ),
        migrations.AddField(
            model_name='appellationsyn',
            name='id_app_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appellation_ref', to='appellation.appellation'),
        ),
        migrations.AddField(
            model_name='appellationsyn',
            name='id_app_syn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appellation_syn', to='appellation.appellation'),
        ),
        migrations.AddField(
            model_name='adminzone',
            name='link_za_zadm',
            field=models.ManyToManyField(blank=True, through='appellation.LinkZappZadmin', to='appellation.AppellationZone'),
        ),
        migrations.AddField(
            model_name='appellation',
            name='app_syn',
            field=models.ManyToManyField(blank=True, through='appellation.AppellationSyn', to='appellation.Appellation'),
        ),
    ]
