# Generated by Django 3.2.9 on 2021-11-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appellation', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('colour', models.CharField(blank=True, default='', max_length=255)),
                ('technical_name', models.TextField(blank=True, default='')),
                ('survey_hectares', models.TextField(blank=True, default='')),
                ('date_servey_hectares', models.DateField(auto_now_add=True)),
                ('comment_grape', models.TextField(blank=True, default='')),
                ('aromas', models.TextField(blank=True, default='')),
                ('description_tastes', models.TextField(blank=True, default='')),
                ('description_visual', models.TextField(blank=True, default='')),
                ('skins', models.TextField(blank=True, default='')),
                ('cultural_aptures', models.TextField(blank=True, default='')),
                ('phenology', models.TextField(blank=True, default='')),
                ('disease_sensitivity', models.TextField(blank=True, default='')),
                ('potential_garde', models.TextField(blank=True, default='')),
                ('yields', models.TextField(blank=True, default='')),
                ('maturity', models.TextField(blank=True, default='')),
                ('berry_pruning', models.TextField(blank=True, default='')),
                ('type_variety', models.TextField(blank=True, default='')),
                ('species', models.TextField(blank=True, default='')),
                ('clones', models.TextField(blank=True, default='')),
                ('year_cross', models.TextField(blank=True, default='')),
                ('creator', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appellation.country')),
            ],
            options={
                'verbose_name': 'Grape',
                'verbose_name_plural': 'Grapes',
            },
        ),
        migrations.CreateModel(
            name='GrapeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity_taste', models.IntegerField(blank=True, default=0)),
                ('alcohol_taste', models.IntegerField(blank=True, default=0)),
                ('body_taste', models.IntegerField(blank=True, default=0)),
                ('aroma_complexity', models.IntegerField(blank=True, default=0)),
                ('aroma_intensity', models.IntegerField(blank=True, default=0)),
                ('aroma_length', models.IntegerField(blank=True, default=0)),
                ('general_note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='GrapeMainAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_accessory', models.TextField(blank=True, default='')),
                ('grape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grape_main_accessory', to='wine.grape')),
            ],
        ),
        migrations.CreateModel(
            name='GrapeAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, default=0)),
                ('main_accessory', models.TextField(blank=True, default='')),
                ('assemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grape_assemble', to='core.assemble')),
                ('grape', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grape_assembles', to='wine.grape')),
            ],
        ),
        migrations.AddField(
            model_name='grape',
            name='grape_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grapes', to='wine.grapeprofile'),
        ),
        migrations.AddField(
            model_name='grape',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wine.grape'),
        ),
    ]
