# Generated by Django 3.2.9 on 2021-11-23 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0009_auto_20211123_1048'),
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grape',
            name='date_servey_hectares',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='DenominationWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.CharField(blank=True, default='', max_length=255)),
                ('wine_cdc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denomination_wine', to='bottle.winecdc')),
            ],
            options={
                'verbose_name': 'Denomination Wine',
                'verbose_name_plural': 'Denominations Wine',
            },
        ),
    ]
