# Generated by Django 3.2.9 on 2021-12-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0016_alter_appellation_sugar_dose'),
        ('bottle', '0014_auto_20211209_1129'),
        ('core', '0004_delete_denominationwine'),
        ('wine', '0002_auto_20211123_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugarDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type_wine', models.TextField(blank=True, default='')),
                ('min_sugar_concentration', models.FloatField(blank=True, default=0)),
                ('max_sugar_concentration', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Dose',
                'verbose_name_plural': 'Doses',
            },
        ),
        migrations.CreateModel(
            name='WineCDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('colour', models.TextField(blank=True, default='')),
                ('type', models.TextField(blank=True, default='')),
                ('comment_descritpion', models.TextField(blank=True, default='')),
                ('appellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wineCDC', to='appellation.appellation')),
                ('assemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winecdc', to='core.assemble')),
                ('sugar_dose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_cdc', to='wine.sugardose')),
                ('wine_profile_cdc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_CDC', to='bottle.wineprofilecdc')),
            ],
            options={
                'verbose_name': 'Wine CDC',
                'verbose_name_plural': 'Wine CDCs',
            },
        ),
        migrations.AlterField(
            model_name='denominationwine',
            name='wine_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denomination_wine', to='wine.winecdc'),
        ),
    ]
