# Generated by Django 3.2.9 on 2022-02-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0018_auto_20220207_1115'),
        ('appellation', '0021_auto_20220207_1115'),
        ('wine', '0007_auto_20211214_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grape',
            name='country',
        ),
        migrations.RemoveField(
            model_name='grape',
            name='grape_profile',
        ),
        migrations.RemoveField(
            model_name='grape',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='grapeassembly',
            name='assemble',
        ),
        migrations.RemoveField(
            model_name='grapeassembly',
            name='grape',
        ),
        migrations.RemoveField(
            model_name='grapemainaccessory',
            name='grape',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='appellation',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='assemble',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='sugar_dose',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='wine_profile_cdc',
        ),
        migrations.DeleteModel(
            name='DenominationWine',
        ),
        migrations.DeleteModel(
            name='Grape',
        ),
        migrations.DeleteModel(
            name='GrapeAssembly',
        ),
        migrations.DeleteModel(
            name='GrapeMainAccessory',
        ),
        migrations.DeleteModel(
            name='GrapeProfile',
        ),
        migrations.DeleteModel(
            name='SugarDose',
        ),
        migrations.DeleteModel(
            name='WineCDC',
        ),
    ]
