# Generated by Django 3.2.9 on 2021-11-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appellation', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(blank=True, default=0)),
                ('gtin', models.IntegerField(blank=True, default=0)),
                ('code', models.CharField(blank=True, default='', max_length=25)),
                ('container', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Bottle',
                'verbose_name_plural': 'Bottles',
            },
        ),
        migrations.CreateModel(
            name='CategoryLexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Lexicon Category',
                'verbose_name_plural': 'Lexicon Categories',
            },
        ),
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='lexicons', to='bottle.categorylexicon')),
            ],
            options={
                'verbose_name': 'Lexicon',
                'verbose_name_plural': 'Lexicons',
            },
        ),
        migrations.CreateModel(
            name='Robe',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name_colour', models.CharField(
                    blank=True, default='', max_length=255)),
                ('value_colour', models.CharField(
                    blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Robes',
            },
        ),
        migrations.CreateModel(
            name='SugarDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type_wine', models.TextField(blank=True, default='')),
                ('min_sugar_concentration', models.FloatField(blank=True, default=0)),
                ('max_sugar_concentration', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Doses',
            },
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('start_apogee', models.DateField(auto_now_add=True)),
                ('apogee', models.DateField(auto_now_add=True)),
                ('end_apogee', models.DateField(auto_now_add=True)),
                ('quality', models.FloatField(blank=True, default=0)),
                ('year', models.DateField(auto_now_add=True)),
                ('year_as_int', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Vintage',
                'verbose_name_plural': 'Vintages',
            },
        ),
        migrations.CreateModel(
            name='WineCDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('colour', models.TextField(blank=True, default='')),
                ('type', models.TextField(blank=True, default='')),
                ('comment_descritpion', models.TextField(blank=True, default='')),
                ('list_denomination_wine', models.TextField(blank=True, default='')),
                ('appellation', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='wineCDC', to='appellation.appellation')),
                ('assemble', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='winecdc', to='core.assemble')),
                ('denomination_wine', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='wineCdc', to='core.denominationwine')),
                ('sugar_dose', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='wine_cdc', to='bottle.sugardose')),
            ],
            options={
                'verbose_name': 'Wine CDC',
                'verbose_name_plural': 'Wine CDCs',
            },
        ),
        migrations.CreateModel(
            name='WineMakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity_taste', models.IntegerField(blank=True, default=0)),
                ('alcohol_taste', models.IntegerField(blank=True, default=0)),
                ('body_taste', models.IntegerField(blank=True, default=0)),
                ('sucrosite_taste', models.IntegerField(blank=True, default=0)),
                ('aroma_complexity', models.IntegerField(blank=True, default=0)),
                ('aroma_intensity', models.IntegerField(blank=True, default=0)),
                ('aroma_length', models.IntegerField(blank=True, default=0)),
                ('general_note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'WineMakerProfile',
                'verbose_name_plural': 'WineMakerProfiles',
            },
        ),
        migrations.CreateModel(
            name='WineProfileCDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity_taste', models.IntegerField(blank=True, default=0)),
                ('alcohol_taste', models.IntegerField(blank=True, default=0)),
                ('body_taste', models.IntegerField(blank=True, default=0)),
                ('aroma_complexity', models.IntegerField(blank=True, default=0)),
                ('aroma_intensity', models.IntegerField(blank=True, default=0)),
                ('aroma_length', models.IntegerField(blank=True, default=0)),
                ('general_note', models.TextField(blank=True, default='')),
                ('robe_description', models.TextField(blank=True, default='')),
                ('fruity_note', models.TextField(blank=True, default='')),
                ('acidity_note', models.TextField(blank=True, default='')),
                ('body_note', models.TextField(blank=True, default='')),
                ('intensity_note', models.TextField(blank=True, default='')),
                ('temperature', models.TextField(blank=True, default='')),
                ('opening_time', models.TextField(blank=True, default='')),
                ('robe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='wine_profile_cdc', to='bottle.robe')),
            ],
            options={
                'verbose_name': 'WineProfileCDCs',
            },
        ),
        migrations.CreateModel(
            name='WineMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('siren', models.TextField(blank=True, default='')),
                ('viticulture', models.TextField(blank=True, default='')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(blank=True, default='')),
                ('gps_location', models.TextField(blank=True, default='')),
                ('type_winemaker', models.TextField(blank=True, default='')),
                ('comment_winemaker', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='winemaker', to='appellation.country')),
                ('winemaker_profile', models.ForeignKey(default='', null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='winemakers', to='bottle.winemakerprofile')),
            ],
            options={
                'verbose_name': 'WineMaker',
                'verbose_name_plural': 'WineMakers',
            },
        ),
        migrations.CreateModel(
            name='WineCDCLexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(blank=True, default=0)),
                ('lexicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='wine_cdc_lexicons', to='bottle.lexicon')),
                ('wine_cdc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='wine_cdc_lexicons', to='bottle.winecdc')),
            ],
            options={
                'verbose_name': 'WineCDCLexicon',
                'verbose_name_plural': 'WineCDCLexicons',
            },
        ),
        migrations.AddField(
            model_name='winecdc',
            name='wine_profile_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='wine_cdc', to='bottle.wineprofilecdc'),
        ),
        migrations.CreateModel(
            name='WineBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_degustation', models.TextField(blank=True, default='')),
                ('comment_vinification', models.TextField(blank=True, default='')),
                ('comment_viticulture', models.TextField(blank=True, default='')),
                ('certification', models.TextField(blank=True, default='')),
                ('alcohol', models.FloatField(blank=True, default=0)),
                ('name_tank', models.TextField(blank=True, default='')),
                ('assemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='wine_bottle_assemble', to='core.assemble')),
                ('vintage', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='wine_bottles', to='bottle.vintage')),
                ('wine_profile_cdc', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='wine_bottle', to='bottle.wineprofilecdc')),
                ('winemaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='wine_container', to='bottle.winemaker')),
            ],
            options={
                'verbose_name': 'Wine Bottle',
                'verbose_name_plural': 'Wine Bottles',
            },
        ),
        migrations.AddField(
            model_name='vintage',
            name='wine_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='vintages', to='bottle.winecdc'),
        ),
        migrations.CreateModel(
            name='NoteGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('wine_bottle', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='note_guides', to='bottle.winebottle')),
            ],
            options={
                'verbose_name': 'Note Guide',
                'verbose_name_plural': 'Note Guides',
            },
        ),
        migrations.CreateModel(
            name='BottlePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting', models.TextField(blank=True, default='')),
                ('definition', models.TextField(blank=True, default='')),
                ('file_name', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.TextField(blank=True, default='')),
                ('type_photo', models.TextField(blank=True, default='')),
                ('media_photo', models.TextField(blank=True, default='')),
                ('bottle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='bottle_photos', to='bottle.bottle')),
            ],
            options={
                'verbose_name': 'Bottle Photo',
                'verbose_name_plural': 'Bottle Photos',
            },
        ),
        migrations.AddField(
            model_name='bottle',
            name='wine_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='bottles', to='bottle.winebottle'),
        ),
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(
                    blank=True, default='', max_length=255)),
                ('profile_wine_cdc', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='bottle.wineprofilecdc')),
            ],
            options={
                'verbose_name': 'Aroma',
                'verbose_name_plural': 'Aromas',
            },
        ),
    ]
