# Generated by Django 3.2.9 on 2021-11-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winecdc',
            name='list_denomination_wine',
        ),
    ]
