# Generated by Django 3.2.9 on 2021-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0003_alter_winemaker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintage',
            name='comment_vintage',
            field=models.TextField(blank=True, default=''),
        ),
    ]
