# Generated by Django 3.2.9 on 2021-11-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0004_vintage_comment_vintage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aroma',
            name='profile_wine_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aromas', to='bottle.wineprofilecdc'),
        ),
    ]
