# Generated by Django 3.2.9 on 2021-11-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0005_alter_aroma_profile_wine_cdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aging', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='wineprofilecdc',
            name='aging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_profile_cdc', to='bottle.agingdefault'),
        ),
    ]
