# Generated by Django 3.2.9 on 2021-11-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0006_auto_20211121_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agingdefault',
            options={'verbose_name': 'Agings'},
        ),
    ]
