# Generated by Django 3.2.9 on 2021-11-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0007_alter_agingdefault_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winecdc',
            name='denomination_wine',
        ),
    ]
