# Generated by Django 3.2.9 on 2021-11-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0009_auto_20211123_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wineprofilecdc',
            options={'verbose_name': 'WineProfileCDC', 'verbose_name_plural': 'WineProfileCDCs'},
        ),
    ]
