# Generated by Django 3.2.9 on 2021-11-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0010_alter_wineprofilecdc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agingdefault',
            options={'verbose_name': 'Aging', 'verbose_name_plural': 'Agings'},
        ),
        migrations.AlterModelOptions(
            name='robe',
            options={'verbose_name': 'Robe', 'verbose_name_plural': 'Robes'},
        ),
        migrations.AlterModelOptions(
            name='sugardose',
            options={'verbose_name': 'Dose', 'verbose_name_plural': 'Doses'},
        ),
    ]
