# Generated by Django 3.2.9 on 2021-12-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0012_alter_winemaker_gps_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vintage',
            name='year_as_int',
        ),
    ]
