# Generated by Django 3.2.9 on 2021-12-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0013_remove_vintage_year_as_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winecdc',
            name='appellation',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='assemble',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='sugar_dose',
        ),
        migrations.RemoveField(
            model_name='winecdc',
            name='wine_profile_cdc',
        ),
    ]
