# Generated by Django 3.2.9 on 2021-12-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appellation', '0017_alter_appellation_sugar_dose'),
        ('wine', '0003_auto_20211209_1129'),
        ('bottle', '0014_auto_20211209_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vintage',
            name='wine_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vintages', to='wine.winecdc'),
        ),
        migrations.AlterField(
            model_name='winecdclexicon',
            name='wine_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_cdc_lexicons', to='wine.winecdc'),
        ),
        migrations.DeleteModel(
            name='SugarDose',
        ),
        migrations.DeleteModel(
            name='WineCDC',
        ),
    ]
