# Generated by Django 3.2.9 on 2021-12-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0015_auto_20211209_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winecdclexicon',
            name='lexicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_cdc_lexicons', to='bottle.lexicon'),
        ),
    ]
