# Generated by Django 3.2.9 on 2022-02-07 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0017_auto_20211210_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('promo_price', models.FloatField(blank=True, null=True)),
                ('start_promotion_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_promotion_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Bottle price',
                'verbose_name_plural': 'Bottles prices',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Range',
                'verbose_name_plural': 'Ranges',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_stock_ext', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('quantity_available', models.IntegerField(blank=True, null=True)),
                ('quantity_ordered', models.IntegerField(blank=True, null=True)),
                ('quantity_reserved', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(blank=True, null=True)),
                ('wine_name', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('subregion', models.TextField(blank=True, null=True)),
                ('appellation', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('grape_assemble', models.TextField(blank=True, null=True)),
                ('colour', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('vintage', models.TextField(blank=True, null=True)),
                ('winemaker', models.TextField(blank=True, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('alcohol', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ranking', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('price_pre_taxe', models.FloatField(blank=True, null=True)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('price_with_taxe', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Stock list',
                'verbose_name_plural': 'Stock lists',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.RemoveField(
            model_name='aroma',
            name='profile_wine_cdc',
        ),
        migrations.RemoveField(
            model_name='lexicon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vintage',
            name='wine_cdc',
        ),
        migrations.RemoveField(
            model_name='winecdclexicon',
            name='lexicon',
        ),
        migrations.RemoveField(
            model_name='winecdclexicon',
            name='wine_cdc',
        ),
        migrations.RemoveField(
            model_name='wineprofilecdc',
            name='aging',
        ),
        migrations.RemoveField(
            model_name='wineprofilecdc',
            name='robe',
        ),
        migrations.RenameField(
            model_name='winemakerprofile',
            old_name='acidity_taste',
            new_name='taste_acidity',
        ),
        migrations.RenameField(
            model_name='winemakerprofile',
            old_name='alcohol_taste',
            new_name='taste_alcohol',
        ),
        migrations.RenameField(
            model_name='winemakerprofile',
            old_name='body_taste',
            new_name='taste_body',
        ),
        migrations.RenameField(
            model_name='winemakerprofile',
            old_name='sucrosite_taste',
            new_name='taste_sucrosite',
        ),
        migrations.AddField(
            model_name='bottle',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bottle',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bottlephoto',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bottlephoto',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='noteguide',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='noteguide',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='winebottle',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='winebottle',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='classement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='google_maps_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='google_place_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='id_import',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='lng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winemakerprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='winemakerprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bottlephoto',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
