# Generated by Django 3.2.9 on 2022-02-07 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alphabet_country_language'),
        ('wine', '0008_auto_20220207_1115'),
        ('productspec', '0001_initial'),
        ('client', '0008_auto_20220207_1115'),
        ('bottle', '0018_auto_20220207_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winebottle',
            name='assemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_bottle_assemble', to='productspec.assemble'),
        ),
        migrations.AlterField(
            model_name='winebottle',
            name='vintage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_bottles', to='productspec.vintage'),
        ),
        migrations.AlterField(
            model_name='winebottle',
            name='wine_profile_cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wine_bottle', to='productspec.wineprofilecdc'),
        ),
        migrations.AlterField(
            model_name='winemaker',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winemaker', to='core.country'),
        ),
        migrations.AlterField(
            model_name='winemaker',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='bottlephoto',
            table='bottle_img',
        ),
        migrations.AlterModelTable(
            name='winebottle',
            table='bottle_product',
        ),
        migrations.AlterModelTable(
            name='winemaker',
            table='bottle_producer',
        ),
        migrations.DeleteModel(
            name='AgingDefault',
        ),
        migrations.DeleteModel(
            name='Aroma',
        ),
        migrations.DeleteModel(
            name='CategoryLexicon',
        ),
        migrations.DeleteModel(
            name='Lexicon',
        ),
        migrations.DeleteModel(
            name='Robe',
        ),
        migrations.DeleteModel(
            name='Vintage',
        ),
        migrations.DeleteModel(
            name='WineCDCLexicon',
        ),
        migrations.DeleteModel(
            name='WineProfileCDC',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='client.client'),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='id_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to='bottle.bottle'),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='id_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocklists', to='bottle.range'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stocklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bottle.stocklist'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='bottle.warehouse'),
        ),
        migrations.AddField(
            model_name='range',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='range', to='client.client'),
        ),
        migrations.AddField(
            model_name='price',
            name='stocklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottle_prices', to='bottle.stocklist'),
        ),
    ]
