# Generated by Django 3.2.9 on 2021-11-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Cooking',
                'verbose_name_plural': 'Cooking',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.TextField(blank=True, default='')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='food_and_wine_pairing.food')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipies',
            },
        ),
        migrations.CreateModel(
            name='Spice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Spice',
                'verbose_name_plural': 'Spices',
            },
        ),
        migrations.CreateModel(
            name='RecipeSpice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_spices', to='food_and_wine_pairing.recipe')),
                ('spice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_spices', to='food_and_wine_pairing.spice')),
            ],
            options={
                'verbose_name': 'Recipe spice relation',
                'verbose_name_plural': 'Recipe spice relations',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredient', to='food_and_wine_pairing.ingredient')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='food_and_wine_pairing.recipe')),
            ],
            options={
                'verbose_name': 'Recipe ingredient relation',
                'verbose_name_plural': 'Recipe ingredient relations',
            },
        ),
        migrations.CreateModel(
            name='RecipeCooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('cooking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_cooking', to='food_and_wine_pairing.cooking')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_cooking', to='food_and_wine_pairing.recipe')),
            ],
            options={
                'verbose_name': 'Recipe cooking relation',
                'verbose_name_plural': 'Recipe cooking relations',
            },
        ),
        migrations.CreateModel(
            name='FoodWineMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.TextField(blank=True, default='')),
                ('vineyard', models.TextField(blank=True, default='')),
                ('appellation', models.TextField(blank=True, default='')),
                ('dgs', models.TextField(blank=True, default='')),
                ('grape', models.TextField(blank=True, default='')),
                ('type', models.TextField(blank=True, default='')),
                ('colour', models.TextField(blank=True, default='')),
                ('dose', models.TextField(blank=True, default='')),
                ('denomination_wine', models.TextField(blank=True, default='')),
                ('source', models.TextField(blank=True, default='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_wine_match', to='food_and_wine_pairing.food')),
            ],
            options={
                'verbose_name': 'Food Wine Match',
                'verbose_name_plural': 'Food Wine Matchs',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='food_and_wine_pairing.foodcategory'),
        ),
    ]
