# Generated by Django 3.2.9 on 2021-11-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_wine_pairing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwinematch',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
