# Generated by Django 3.2.9 on 2021-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_wine_pairing', '0002_alter_foodwinematch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='appellation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='colour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='denomination_wine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='dgs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='dose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='grape',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodwinematch',
            name='vineyard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipecooking',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipespice',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spice',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spice',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
